alter table "public"."todo" drop constraint "todo_pkey";

drop index if exists "public"."todo_pkey";

drop table "public"."todo";

create table "public"."todos" (
    "id" bigint generated by default as identity not null,
    "text" character varying not null,
    "complete" boolean not null default false,
    "created_at" timestamp with time zone not null default now()
);


CREATE UNIQUE INDEX todo_pkey ON public.todos USING btree (id);

alter table "public"."todos" add constraint "todo_pkey" PRIMARY KEY using index "todo_pkey";


